//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by slsvcutil, version 2.0.5.0
// 
namespace chapter4.Web
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookInfo", Namespace="http://schemas.datacontract.org/2004/07/chapter4.Web")]
    public partial class BookInfo : object
    {
        
        private string AuthorField;
        
        private string[] ChaptersField;
        
        private string ISBNField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Chapters
        {
            get
            {
                return this.ChaptersField;
            }
            set
            {
                this.ChaptersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN
        {
            get
            {
                return this.ISBNField;
            }
            set
            {
                this.ISBNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="GetBookInfo")]
public interface GetBookInfo
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetBookInfo/GetByTitle", ReplyAction="urn:GetBookInfo/GetByTitleResponse")]
    System.IAsyncResult BeginGetByTitle(string Title, System.AsyncCallback callback, object asyncState);
    
    chapter4.Web.BookInfo EndGetByTitle(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:GetBookInfo/GetAllTitle", ReplyAction="urn:GetBookInfo/GetAllTitleResponse")]
    System.IAsyncResult BeginGetAllTitle(System.AsyncCallback callback, object asyncState);
    
    string[] EndGetAllTitle(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface GetBookInfoChannel : GetBookInfo, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetByTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetByTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public chapter4.Web.BookInfo Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((chapter4.Web.BookInfo)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetAllTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetAllTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetBookInfoClient : System.ServiceModel.ClientBase<GetBookInfo>, GetBookInfo
{
    
    private BeginOperationDelegate onBeginGetByTitleDelegate;
    
    private EndOperationDelegate onEndGetByTitleDelegate;
    
    private System.Threading.SendOrPostCallback onGetByTitleCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetAllTitleDelegate;
    
    private EndOperationDelegate onEndGetAllTitleDelegate;
    
    private System.Threading.SendOrPostCallback onGetAllTitleCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public GetBookInfoClient()
    {
    }
    
    public GetBookInfoClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public GetBookInfoClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetBookInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public GetBookInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public event System.EventHandler<GetByTitleCompletedEventArgs> GetByTitleCompleted;
    
    public event System.EventHandler<GetAllTitleCompletedEventArgs> GetAllTitleCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult GetBookInfo.BeginGetByTitle(string Title, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetByTitle(Title, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    chapter4.Web.BookInfo GetBookInfo.EndGetByTitle(System.IAsyncResult result)
    {
        return base.Channel.EndGetByTitle(result);
    }
    
    private System.IAsyncResult OnBeginGetByTitle(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string Title = ((string)(inValues[0]));
        return ((GetBookInfo)(this)).BeginGetByTitle(Title, callback, asyncState);
    }
    
    private object[] OnEndGetByTitle(System.IAsyncResult result)
    {
        chapter4.Web.BookInfo retVal = ((GetBookInfo)(this)).EndGetByTitle(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetByTitleCompleted(object state)
    {
        if ((this.GetByTitleCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetByTitleCompleted(this, new GetByTitleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetByTitleAsync(string Title)
    {
        this.GetByTitleAsync(Title, null);
    }
    
    public void GetByTitleAsync(string Title, object userState)
    {
        if ((this.onBeginGetByTitleDelegate == null))
        {
            this.onBeginGetByTitleDelegate = new BeginOperationDelegate(this.OnBeginGetByTitle);
        }
        if ((this.onEndGetByTitleDelegate == null))
        {
            this.onEndGetByTitleDelegate = new EndOperationDelegate(this.OnEndGetByTitle);
        }
        if ((this.onGetByTitleCompletedDelegate == null))
        {
            this.onGetByTitleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetByTitleCompleted);
        }
        base.InvokeAsync(this.onBeginGetByTitleDelegate, new object[] {
                    Title}, this.onEndGetByTitleDelegate, this.onGetByTitleCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult GetBookInfo.BeginGetAllTitle(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAllTitle(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string[] GetBookInfo.EndGetAllTitle(System.IAsyncResult result)
    {
        return base.Channel.EndGetAllTitle(result);
    }
    
    private System.IAsyncResult OnBeginGetAllTitle(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((GetBookInfo)(this)).BeginGetAllTitle(callback, asyncState);
    }
    
    private object[] OnEndGetAllTitle(System.IAsyncResult result)
    {
        string[] retVal = ((GetBookInfo)(this)).EndGetAllTitle(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetAllTitleCompleted(object state)
    {
        if ((this.GetAllTitleCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetAllTitleCompleted(this, new GetAllTitleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetAllTitleAsync()
    {
        this.GetAllTitleAsync(null);
    }
    
    public void GetAllTitleAsync(object userState)
    {
        if ((this.onBeginGetAllTitleDelegate == null))
        {
            this.onBeginGetAllTitleDelegate = new BeginOperationDelegate(this.OnBeginGetAllTitle);
        }
        if ((this.onEndGetAllTitleDelegate == null))
        {
            this.onEndGetAllTitleDelegate = new EndOperationDelegate(this.OnEndGetAllTitle);
        }
        if ((this.onGetAllTitleCompletedDelegate == null))
        {
            this.onGetAllTitleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllTitleCompleted);
        }
        base.InvokeAsync(this.onBeginGetAllTitleDelegate, null, this.onEndGetAllTitleDelegate, this.onGetAllTitleCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override GetBookInfo CreateChannel()
    {
        return new GetBookInfoClientChannel(this);
    }
    
    private class GetBookInfoClientChannel : ChannelBase<GetBookInfo>, GetBookInfo
    {
        
        public GetBookInfoClientChannel(System.ServiceModel.ClientBase<GetBookInfo> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetByTitle(string Title, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = Title;
            System.IAsyncResult _result = base.BeginInvoke("GetByTitle", _args, callback, asyncState);
            return _result;
        }
        
        public chapter4.Web.BookInfo EndGetByTitle(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            chapter4.Web.BookInfo _result = ((chapter4.Web.BookInfo)(base.EndInvoke("GetByTitle", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetAllTitle(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetAllTitle", _args, callback, asyncState);
            return _result;
        }
        
        public string[] EndGetAllTitle(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string[] _result = ((string[])(base.EndInvoke("GetAllTitle", _args, result)));
            return _result;
        }
    }
}
