<?xml version="1.0" encoding="utf-8"?>
<Database Name="WcfAjax" EntityNamespace="Amazon" ContextNamespace="Amazon" Class="AmazonContext" BaseType="Westwind.BusinessFramework.LinqToSql.DataContextSql" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=DevSamples;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DevSampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AmazonBooks" Member="AmazonBooks">
    <Type Name="AmazonBook">
      <Column Name="Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ISBN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AmazonUrl" Type="System.String" DbType="VarChar(512)" CanBeNull="true" />
      <Column Name="AmazonImage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AmazonSmallImage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="Published" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Review" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Highlight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Entered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="tStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.AmazonLookups" Member="AmazonLookupLists">
    <Type Name="AmazonLookupList">
      <Column Name="Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="cData" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="cData1" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="cData2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="iData" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tStamp" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
    </Type>
  </Table>
</Database>