//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace NCrawler.SQLite
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NCrawlerEntitiesSQLite : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NCrawlerEntitiesSQLite object using the connection string found in the 'NCrawlerEntitiesSQLite' section of the application configuration file.
        /// </summary>
        public NCrawlerEntitiesSQLite() : base("name=NCrawlerEntitiesSQLite", "NCrawlerEntitiesSQLite")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NCrawlerEntitiesSQLite object.
        /// </summary>
        public NCrawlerEntitiesSQLite(string connectionString) : base(connectionString, "NCrawlerEntitiesSQLite")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NCrawlerEntitiesSQLite object.
        /// </summary>
        public NCrawlerEntitiesSQLite(EntityConnection connection) : base(connection, "NCrawlerEntitiesSQLite")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CrawlHistory> CrawlHistories
        {
            get
            {
                if ((_CrawlHistories == null))
                {
                    _CrawlHistories = base.CreateObjectSet<CrawlHistory>("CrawlHistories");
                }
                return _CrawlHistories;
            }
        }
        private ObjectSet<CrawlHistory> _CrawlHistories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CrawlQueue> CrawlQueues
        {
            get
            {
                if ((_CrawlQueues == null))
                {
                    _CrawlQueues = base.CreateObjectSet<CrawlQueue>("CrawlQueues");
                }
                return _CrawlQueues;
            }
        }
        private ObjectSet<CrawlQueue> _CrawlQueues;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CrawlHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCrawlHistories(CrawlHistory crawlHistory)
        {
            base.AddObject("CrawlHistories", crawlHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CrawlQueues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCrawlQueues(CrawlQueue crawlQueue)
        {
            base.AddObject("CrawlQueues", crawlQueue);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCrawlerModel", Name="CrawlHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CrawlHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CrawlHistory object.
        /// </summary>
        /// <param name="key">Initial value of the Key property.</param>
        public static CrawlHistory CreateCrawlHistory(global::System.String key)
        {
            CrawlHistory crawlHistory = new CrawlHistory();
            crawlHistory.Key = key;
            return crawlHistory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                if (_Key != value)
                {
                    OnKeyChanging(value);
                    ReportPropertyChanging("Key");
                    _Key = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Key");
                    OnKeyChanged();
                }
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                OnGroupIdChanging(value);
                ReportPropertyChanging("GroupId");
                _GroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupId");
                OnGroupIdChanged();
            }
        }
        private Nullable<global::System.Int64> _GroupId;
        partial void OnGroupIdChanging(Nullable<global::System.Int64> value);
        partial void OnGroupIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NCrawlerModel", Name="CrawlQueue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CrawlQueue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CrawlQueue object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="groupId">Initial value of the GroupId property.</param>
        public static CrawlQueue CreateCrawlQueue(global::System.Int64 id, global::System.Int64 groupId)
        {
            CrawlQueue crawlQueue = new CrawlQueue();
            crawlQueue.Id = id;
            crawlQueue.GroupId = groupId;
            return crawlQueue;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                OnGroupIdChanging(value);
                ReportPropertyChanging("GroupId");
                _GroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupId");
                OnGroupIdChanged();
            }
        }
        private global::System.Int64 _GroupId;
        partial void OnGroupIdChanging(global::System.Int64 value);
        partial void OnGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] SerializedData
        {
            get
            {
                return StructuralObject.GetValidValue(_SerializedData);
            }
            set
            {
                OnSerializedDataChanging(value);
                ReportPropertyChanging("SerializedData");
                _SerializedData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SerializedData");
                OnSerializedDataChanged();
            }
        }
        private global::System.Byte[] _SerializedData;
        partial void OnSerializedDataChanging(global::System.Byte[] value);
        partial void OnSerializedDataChanged();

        #endregion
    
    }

    #endregion
    
}
