//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westwind.WebToolkit.Ajax {
    
    
    public partial class jqGrid {
        
        /// <summary>
        /// ViewSourceControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Manoli.Utils.CSharpFormat.ViewSourceControl ViewSourceControl;
        
        /// <summary>
        /// ViewSourceControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Manoli.Utils.CSharpFormat.ViewSourceControl ViewSourceControl1;
        
        /// <summary>
        /// Proxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Westwind.Web.Controls.AjaxMethodCallback Proxy;
        
        /// <summary>
        /// scripts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Westwind.Web.Controls.ScriptContainer scripts;
    }
}
