<?xml version="1.0" encoding="utf-8"?>
<Database Name="TimeTrakker" EntityNamespace="TimeTrakker" ContextNamespace="TimeTrakker" Class="TimeTrakkerContext" BaseType="Westwind.BusinessFramework.LinqToSql.DataContextSql" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=TimeTrakker_Westwind;Integrated Security=True" SettingsObjectName="TimeTrakker.Properties.Settings" SettingsPropertyName="TimeTrakkerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Projects" Member="ProjectEntities">
    <Type Name="ProjectEntity">
      <Column Name="Pk" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerPk" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Entered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tversion" AccessModifier="Protected" Type="System.Byte[]" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="ProjectEntity_EntryEntity" Member="Entries" AccessModifier="Internal" ThisKey="Pk" OtherKey="ProjectPk" Type="EntryEntity" />
      <Association Name="CustomerEntity_ProjectEntity" Member="Customer" ThisKey="CustomerPk" OtherKey="Pk" Type="CustomerEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoices" Member="InvoiceEntities">
    <Type Name="InvoiceEntity">
      <Column Name="Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerPk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoiceNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="InvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Paid" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="tversion" AccessModifier="Protected" Type="System.Byte[]" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="InvoiceEntity_EntryEntity" Member="Entries" AccessModifier="Internal" ThisKey="Pk" OtherKey="InvoicePk" Type="EntryEntity" />
      <Association Name="CustomerEntity_InvoiceEntity" Member="Customer" ThisKey="CustomerPk" OtherKey="Pk" Type="CustomerEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lookups" Member="LookupEntities">
    <Type Name="LookupEntity">
      <Column Name="pk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cdata" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cdata1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cdata2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="idata" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tversion" Type="System.Byte[]" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="UserEntities">
    <Type Name="UserEntity">
      <Column Name="Pk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserCompany" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastCustomer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastProject" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tversion" Type="System.Byte[]" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="UserEntity_EntryEntity" Member="Entries" AccessModifier="Internal" ThisKey="Pk" OtherKey="UserPk" Type="EntryEntity" />
    </Type>
  </Table>
  <Table Name="dbo.Entries" Member="EntryEntities">
    <Type Name="EntryEntity">
      <Column Name="Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" CanBeNull="false" IsVersion="true" />
      <Column Name="CustomerPk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectPk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InvoicePk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserPk" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" />
      <Column Name="TimeIn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TimeOut" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PunchedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Qty" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TotalHours" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ItemTotal" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Taxable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Billed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Imported" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xml" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="tversion" Type="System.Byte[]" DbType="rowversion NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="InvoiceEntity_EntryEntity" Member="InvoiceEntity" ThisKey="InvoicePk" OtherKey="Pk" Type="InvoiceEntity" IsForeignKey="true" />
      <Association Name="ProjectEntity_EntryEntity" Member="ProjectEntity" ThisKey="ProjectPk" OtherKey="Pk" Type="ProjectEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="UserEntity_EntryEntity" Member="UserEntity" ThisKey="UserPk" OtherKey="Pk" Type="UserEntity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="CustomerEntities">
    <Type Name="CustomerEntity">
      <Column Name="Pk" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(2048) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="State" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Zip" Type="System.String" DbType="NChar(12) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CountryId" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Entered" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Updated" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastOrder" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BillingRate" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Xml" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="tversion" Type="System.Byte[]" DbType="rowversion NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="CustomerEntity_ProjectEntity" Member="ProjectEntities" AccessModifier="Internal" ThisKey="Pk" OtherKey="CustomerPk" Type="ProjectEntity" />
      <Association Name="CustomerEntity_InvoiceEntity" Member="InvoiceEntities" AccessModifier="Internal" ThisKey="Pk" OtherKey="CustomerPk" Type="InvoiceEntity" />
    </Type>
  </Table>
  <Function Name="dbo.ww_NewIDSafe" Method="ww_NewIDSafe">
    <Parameter Name="cName" Type="System.String" DbType="Char(30)" />
    <Parameter Name="cPkField" Type="System.String" DbType="Char(15)" />
    <Parameter Name="nRetval" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>